#!/usr/bin/env python3
"""Regenerate custom-themes.css by inlining the theme files listed in
custom-themes.manifest.css, so the LMS makes one @import instead of one
per theme. Run after editing any theme-erau-*.css file or the manifest."""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
MANIFEST = ROOT / "custom-themes.manifest.css"
OUTPUT = ROOT / "custom-themes.css"

IMPORT_RE = re.compile(r"^@import\s+url\([\"']?[^)\"']*/([^/)\"']+\.css)[\"']?\);\s*$")

BANNER = """/* AUTO-GENERATED FILE — DO NOT EDIT DIRECTLY.
   Generated by build.py from custom-themes.manifest.css and the
   theme-erau-*.css files. Edit those, then run `python3 build.py`. */
"""


def build():
    manifest_lines = MANIFEST.read_text().splitlines()
    out = [BANNER]

    # Skip the manifest's own leading comment block (up to the first blank
    # line) — it documents the manifest, not the generated output.
    if manifest_lines and manifest_lines[0].lstrip().startswith("/*"):
        blank_idx = manifest_lines.index("")
        manifest_lines = manifest_lines[blank_idx + 1:]

    for line in manifest_lines:
        match = IMPORT_RE.match(line.strip())
        if not match:
            out.append(line)
            continue

        theme_file = ROOT / match.group(1)
        if not theme_file.exists():
            sys.exit(f"error: {theme_file.name} referenced in manifest but not found")

        out.append(f"/* --- {theme_file.name} --- */")
        out.append(theme_file.read_text().rstrip("\n"))

    OUTPUT.write_text("\n".join(out) + "\n")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    build()
